"""Handler registry — maps (category, sub_intent) to handler functions."""
from __future__ import annotations

from typing import Callable

import pandas as pd

from api.handlers.base import HandlerResult
from api.handlers.stats_handler import StatsHandler
from api.handlers.clean_handler import CleanHandler
from api.handlers.transform_handler import TransformHandler
from api.handlers.viz_handler import VizHandler
from api.handlers.feature_handler import FeatureHandler
from api.handlers.nlp_handler import NlpHandler
from api.handlers.analysis_handler import AnalysisHandler

HandlerFunc = Callable[[pd.DataFrame, dict], HandlerResult]

HANDLER_REGISTRY: dict[tuple[str, str], HandlerFunc] = {
    # Stats
    ("stats", "describe"):          StatsHandler.handle_describe,
    ("stats", "shape"):             StatsHandler.handle_shape,
    ("stats", "null_report"):       StatsHandler.handle_null_report,
    ("stats", "value_counts"):      StatsHandler.handle_value_counts,
    ("stats", "unique_values"):     StatsHandler.handle_unique_values,
    ("stats", "dtypes"):            StatsHandler.handle_dtypes,
    ("stats", "correlation"):       StatsHandler.handle_correlation,
    ("stats", "skewness"):          StatsHandler.handle_skewness,
    ("stats", "outlier_report"):    StatsHandler.handle_outlier_report,
    ("stats", "duplicate_report"):  StatsHandler.handle_duplicate_report,
    ("stats", "cross_tab"):         StatsHandler.handle_cross_tab,
    ("stats", "percentile"):        StatsHandler.handle_percentile,
    ("stats", "normality_test"):    StatsHandler.handle_normality_test,
    ("stats", "class_balance"):     StatsHandler.handle_class_balance,
    ("stats", "top_correlations"):  StatsHandler.handle_top_correlations,
    ("stats", "kurtosis"):          StatsHandler.handle_kurtosis,
    ("stats", "zero_report"):       StatsHandler.handle_zero_report,
    ("stats", "cardinality_report"):StatsHandler.handle_cardinality_report,
    ("stats", "mode_report"):       StatsHandler.handle_mode_report,
    ("stats", "variance_report"):   StatsHandler.handle_variance_report,
    ("stats", "range_report"):      StatsHandler.handle_range_report,
    ("stats", "iqr_report"):        StatsHandler.handle_iqr_report,
    ("stats", "z_score_report"):    StatsHandler.handle_z_score_report,
    ("stats", "chi2_test"):         StatsHandler.handle_chi2_test,
    ("stats", "t_test"):            StatsHandler.handle_t_test,
    ("stats", "anova_test"):        StatsHandler.handle_anova_test,
    ("stats", "mann_whitney"):      StatsHandler.handle_mann_whitney,
    ("stats", "ks_test"):           StatsHandler.handle_ks_test,
    ("stats", "frequency_table"):   StatsHandler.handle_frequency_table,
    ("stats", "coefficient_variation"): StatsHandler.handle_coefficient_variation,
    ("stats", "correlation_rank"):  StatsHandler.handle_correlation_rank,
    ("stats", "entropy_report"):    StatsHandler.handle_entropy_report,
    ("stats", "gini_report"):       StatsHandler.handle_gini_report,
    ("stats", "missing_pattern"):   StatsHandler.handle_missing_pattern,
    ("stats", "quantile_detail"):   StatsHandler.handle_quantile_detail,
    ("stats", "group_stats"):       StatsHandler.handle_group_stats,
    ("stats", "column_compare"):    StatsHandler.handle_column_compare,
    ("stats", "mutual_info_report"):StatsHandler.handle_mutual_info_report,
    ("stats", "summary_extended"):  StatsHandler.handle_summary_extended,
    ("stats", "ratio_report"):      StatsHandler.handle_ratio_report,
    ("stats", "distribution_fit"):  StatsHandler.handle_distribution_fit,
    ("stats", "stability_report"):  StatsHandler.handle_stability_report,
    ("stats", "pairwise_stats"):    StatsHandler.handle_pairwise_stats,
    ("stats", "time_stats"):        StatsHandler.handle_time_stats,
    ("stats", "top_bottom_values"): StatsHandler.handle_top_bottom_values,
    ("stats", "memory_report"):     StatsHandler.handle_memory_report,
    ("stats", "cluster_tendency"):  StatsHandler.handle_cluster_tendency,
    ("stats", "sparsity_report"):   StatsHandler.handle_sparsity_report,
    ("stats", "data_sample"):       StatsHandler.handle_data_sample,
    ("stats", "normality_comprehensive"): StatsHandler.handle_normality_comprehensive,
    # Clean
    ("clean", "drop_nulls"):        CleanHandler.handle_drop_nulls,
    ("clean", "fill_nulls"):        CleanHandler.handle_fill_nulls,
    ("clean", "remove_duplicates"): CleanHandler.handle_remove_duplicates,
    ("clean", "fix_dtypes"):        CleanHandler.handle_fix_dtypes,
    ("clean", "rename_column"):     CleanHandler.handle_rename_column,
    ("clean", "drop_column"):       CleanHandler.handle_drop_column,
    ("clean", "strip_whitespace"):    CleanHandler.handle_strip_whitespace,
    ("clean", "replace_values"):     CleanHandler.handle_replace_values,
    ("clean", "lowercase_columns"):  CleanHandler.handle_lowercase_columns,
    ("clean", "drop_constant"):      CleanHandler.handle_drop_constant,
    ("clean", "clip_outliers"):       CleanHandler.handle_clip_outliers,
    ("clean", "change_dtype"):       CleanHandler.handle_change_dtype,
    ("clean", "fill_interpolate"):   CleanHandler.handle_fill_interpolate,
    ("clean", "remove_outliers"):    CleanHandler.handle_remove_outliers,
    ("clean", "lowercase_values"):   CleanHandler.handle_lowercase_values,
    ("clean", "map_values"):         CleanHandler.handle_map_values,
    ("clean", "reset_index"):        CleanHandler.handle_reset_index,
    ("clean", "fill_with_value"):    CleanHandler.handle_fill_with_value,
    ("clean", "deduplicate_by"):     CleanHandler.handle_deduplicate_by,
    ("clean", "drop_id_columns"):    CleanHandler.handle_drop_id_columns,
    ("clean", "fix_numeric_strings"):   CleanHandler.handle_fix_numeric_strings,
    ("clean", "clean_column_names"):    CleanHandler.handle_clean_column_names,
    ("clean", "remove_empty_rows"):     CleanHandler.handle_remove_empty_rows,
    ("clean", "fill_mode"):             CleanHandler.handle_fill_mode,
    ("clean", "fill_forward_backward"): CleanHandler.handle_fill_forward_backward,
    ("clean", "fix_boolean"):           CleanHandler.handle_fix_boolean,
    ("clean", "fix_encoding"):          CleanHandler.handle_fix_encoding,
    ("clean", "remove_html_tags"):      CleanHandler.handle_remove_html_tags,
    ("clean", "clean_currency"):        CleanHandler.handle_clean_currency,
    ("clean", "standardize_dates"):     CleanHandler.handle_standardize_dates,
    ("clean", "remove_non_ascii"):      CleanHandler.handle_remove_non_ascii,
    ("clean", "remove_special_chars"):  CleanHandler.handle_remove_special_chars,
    ("clean", "normalize_text_case"):   CleanHandler.handle_normalize_text_case,
    ("clean", "cap_outliers_percentile"): CleanHandler.handle_cap_outliers_percentile,
    ("clean", "fill_median_by_group"):  CleanHandler.handle_fill_median_by_group,
    ("clean", "remove_zero_rows"):      CleanHandler.handle_remove_zero_rows,
    ("clean", "remove_negative"):       CleanHandler.handle_remove_negative,
    ("clean", "standardize_categories"): CleanHandler.handle_standardize_categories,
    ("clean", "remove_high_null_cols"): CleanHandler.handle_remove_high_null_cols,
    ("clean", "clean_phone_numbers"):   CleanHandler.handle_clean_phone_numbers,
    ("clean", "split_name"):            CleanHandler.handle_split_name,
    ("clean", "fix_whitespace_names"):  CleanHandler.handle_fix_whitespace_names,
    ("clean", "remove_urls"):           CleanHandler.handle_remove_urls,
    ("clean", "remove_emails"):         CleanHandler.handle_remove_emails,
    ("clean", "fix_mixed_types"):       CleanHandler.handle_fix_mixed_types,
    ("clean", "fill_with_distribution"): CleanHandler.handle_fill_with_distribution,
    ("clean", "remove_rare_categories"): CleanHandler.handle_remove_rare_categories,
    ("clean", "dedup_keep_latest"):     CleanHandler.handle_dedup_keep_latest,
    ("clean", "fix_date_outliers"):     CleanHandler.handle_fix_date_outliers,
    ("clean", "clean_text_whitespace"): CleanHandler.handle_clean_text_whitespace,
    # Transform
    ("transform", "filter"):         TransformHandler.handle_filter,
    ("transform", "assign_value"):   TransformHandler.handle_assign_value,
    ("transform", "sort"):           TransformHandler.handle_sort,
    ("transform", "groupby_agg"):    TransformHandler.handle_groupby_agg,
    ("transform", "add_column"):     TransformHandler.handle_add_column,
    ("transform", "encode_label"):   TransformHandler.handle_encode_label,
    ("transform", "encode_onehot"):  TransformHandler.handle_encode_onehot,
    ("transform", "scale_minmax"):   TransformHandler.handle_scale_minmax,
    ("transform", "scale_standard"): TransformHandler.handle_scale_standard,
    ("transform", "bin_column"):     TransformHandler.handle_bin_column,
    ("transform", "inject_null"):    TransformHandler.handle_inject_null,
    ("transform", "sample_rows"):    TransformHandler.handle_sample_rows,
    ("transform", "head"):             TransformHandler.handle_head,
    ("transform", "tail"):             TransformHandler.handle_tail,
    ("transform", "pivot"):            TransformHandler.handle_pivot,
    ("transform", "melt"):             TransformHandler.handle_melt,
    ("transform", "scale_robust"):     TransformHandler.handle_scale_robust,
    ("transform", "nlargest"):         TransformHandler.handle_nlargest,
    ("transform", "nsmallest"):        TransformHandler.handle_nsmallest,
    ("transform", "rank"):             TransformHandler.handle_rank,
    ("transform", "cumulative"):       TransformHandler.handle_cumulative,
    ("transform", "rolling"):          TransformHandler.handle_rolling,
    ("transform", "round_values"):     TransformHandler.handle_round_values,
    ("transform", "split_column"):     TransformHandler.handle_split_column,
    ("transform", "concat_columns"):   TransformHandler.handle_concat_columns,
    ("transform", "qcut"):             TransformHandler.handle_qcut,
    ("transform", "merge"):            TransformHandler.handle_merge,
    ("transform", "transpose"):        TransformHandler.handle_transpose,
    ("transform", "drop_rows"):        TransformHandler.handle_drop_rows,
    ("transform", "shuffle"):          TransformHandler.handle_shuffle,
    ("transform", "train_test_split"): TransformHandler.handle_train_test_split,
    ("transform", "clip"):             TransformHandler.handle_clip,
    ("transform", "where"):            TransformHandler.handle_where,
    ("transform", "explode"):          TransformHandler.handle_explode,
    ("transform", "encode_binary"):    TransformHandler.handle_encode_binary,
    ("transform", "pct_change"):       TransformHandler.handle_pct_change,
    ("transform", "normalize_pct"):    TransformHandler.handle_normalize_pct,
    ("transform", "apply_expr"):       TransformHandler.handle_apply_expr,
    ("transform", "flatten_columns"):  TransformHandler.handle_flatten_columns,
    ("transform", "resample"):         TransformHandler.handle_resample,
    ("transform", "cross_join"):       TransformHandler.handle_cross_join,
    ("transform", "encode_ordinal"):   TransformHandler.handle_encode_ordinal,
    ("transform", "shift_column"):     TransformHandler.handle_shift_column,
    ("transform", "winsorize"):        TransformHandler.handle_winsorize,
    ("transform", "stack_columns"):    TransformHandler.handle_stack_columns,
    ("transform", "unstack_column"):   TransformHandler.handle_unstack_column,
    ("transform", "reorder_columns"):  TransformHandler.handle_reorder_columns,
    ("transform", "duplicate_column"): TransformHandler.handle_duplicate_column,
    ("transform", "fill_forward"):     TransformHandler.handle_fill_forward,
    ("transform", "interpolate_values"): TransformHandler.handle_interpolate_values,
    # Viz
    ("viz", "bar_chart"):          VizHandler.handle_bar_chart,
    ("viz", "histogram"):          VizHandler.handle_histogram,
    ("viz", "scatter"):            VizHandler.handle_scatter,
    ("viz", "line_chart"):         VizHandler.handle_line_chart,
    ("viz", "box_plot"):           VizHandler.handle_box_plot,
    ("viz", "violin_plot"):        VizHandler.handle_violin_plot,
    ("viz", "heatmap"):            VizHandler.handle_heatmap,
    ("viz", "pie_chart"):          VizHandler.handle_pie_chart,
    ("viz", "pairplot"):           VizHandler.handle_pairplot,
    ("viz", "missing_heatmap"):    VizHandler.handle_missing_heatmap,
    ("viz", "count_plot"):         VizHandler.handle_count_plot,
    ("viz", "time_series"):        VizHandler.handle_time_series,
    ("viz", "bubble_chart"):       VizHandler.handle_bubble_chart,
    ("viz", "treemap"):            VizHandler.handle_treemap,
    ("viz", "sunburst"):           VizHandler.handle_sunburst,
    ("viz", "parallel_coords"):    VizHandler.handle_parallel_coords,
    ("viz", "distribution"):       VizHandler.handle_distribution,
    ("viz", "stacked_bar"):        VizHandler.handle_stacked_bar,
    ("viz", "area_chart"):         VizHandler.handle_area_chart,
    ("viz", "qq_plot"):            VizHandler.handle_qq_plot,
    ("viz", "density_plot"):       VizHandler.handle_density_plot,
    ("viz", "strip_plot"):         VizHandler.handle_strip_plot,
    ("viz", "donut_chart"):        VizHandler.handle_donut_chart,
    ("viz", "grouped_bar"):        VizHandler.handle_grouped_bar,
    ("viz", "percent_bar"):        VizHandler.handle_percent_bar,
    ("viz", "pareto_chart"):       VizHandler.handle_pareto_chart,
    ("viz", "waterfall_chart"):    VizHandler.handle_waterfall_chart,
    ("viz", "funnel_chart"):       VizHandler.handle_funnel_chart,
    ("viz", "radar_chart"):        VizHandler.handle_radar_chart,
    ("viz", "lollipop_chart"):     VizHandler.handle_lollipop_chart,
    ("viz", "dual_axis"):          VizHandler.handle_dual_axis,
    ("viz", "histogram_2d"):       VizHandler.handle_histogram_2d,
    ("viz", "ecdf_plot"):          VizHandler.handle_ecdf_plot,
    ("viz", "step_chart"):         VizHandler.handle_step_chart,
    ("viz", "error_bar_chart"):    VizHandler.handle_error_bar_chart,
    ("viz", "ridgeline"):          VizHandler.handle_ridgeline,
    ("viz", "dot_plot"):           VizHandler.handle_dot_plot,
    ("viz", "polar_chart"):        VizHandler.handle_polar_chart,
    ("viz", "sankey_chart"):       VizHandler.handle_sankey_chart,
    ("viz", "candlestick"):        VizHandler.handle_candlestick,
    ("viz", "contour_plot"):       VizHandler.handle_contour_plot,
    ("viz", "cumulative_line"):    VizHandler.handle_cumulative_line,
    ("viz", "null_bar"):           VizHandler.handle_null_bar,
    ("viz", "top_n_bar"):          VizHandler.handle_top_n_bar,
    ("viz", "correlation_scatter"): VizHandler.handle_correlation_scatter,
    ("viz", "range_plot"):         VizHandler.handle_range_plot,
    ("viz", "swarm_plot"):         VizHandler.handle_swarm_plot,
    ("viz", "comparison_bar"):     VizHandler.handle_comparison_bar,
    ("viz", "marimekko"):          VizHandler.handle_marimekko,
    ("viz", "gauge_chart"):        VizHandler.handle_gauge_chart,
    # Feature
    ("feature", "feature_importance"):  FeatureHandler.handle_feature_importance,
    ("feature", "pca"):                 FeatureHandler.handle_pca,
    ("feature", "correlation_filter"):  FeatureHandler.handle_correlation_filter,
    ("feature", "log_transform"):       FeatureHandler.handle_log_transform,
    ("feature", "variance_filter"):     FeatureHandler.handle_variance_filter,
    ("feature", "polynomial_features"): FeatureHandler.handle_polynomial_features,
    ("feature", "datetime_features"):   FeatureHandler.handle_datetime_features,
    ("feature", "target_encode"):       FeatureHandler.handle_target_encode,
    ("feature", "select_k_best"):       FeatureHandler.handle_select_k_best,
    ("feature", "power_transform"):     FeatureHandler.handle_power_transform,
    ("feature", "ratio_features"):      FeatureHandler.handle_ratio_features,
    ("feature", "frequency_encode"):    FeatureHandler.handle_frequency_encode,
    ("feature", "cyclical_encode"):     FeatureHandler.handle_cyclical_encode,
    ("feature", "sqrt_transform"):      FeatureHandler.handle_sqrt_transform,
    ("feature", "mutual_info"):         FeatureHandler.handle_mutual_info,
    ("feature", "lag_features"):        FeatureHandler.handle_lag_features,
    ("feature", "text_features"):       FeatureHandler.handle_text_features,
    ("feature", "quantile_transform"):  FeatureHandler.handle_quantile_transform,
    ("feature", "diff_features"):       FeatureHandler.handle_diff_features,
    ("feature", "aggregation_features"):FeatureHandler.handle_aggregation_features,
    ("feature", "log1p_transform"):     FeatureHandler.handle_log1p_transform,
    ("feature", "interaction_features"):FeatureHandler.handle_interaction_features,
    ("feature", "bin_numeric"):         FeatureHandler.handle_bin_numeric,
    ("feature", "abs_transform"):       FeatureHandler.handle_abs_transform,
    ("feature", "reciprocal_transform"):FeatureHandler.handle_reciprocal_transform,
    ("feature", "count_encode"):        FeatureHandler.handle_count_encode,
    ("feature", "rare_category_encode"):FeatureHandler.handle_rare_category_encode,
    ("feature", "is_null_features"):    FeatureHandler.handle_is_null_features,
    ("feature", "is_zero_features"):    FeatureHandler.handle_is_zero_features,
    ("feature", "rank_transform"):      FeatureHandler.handle_rank_transform,
    ("feature", "kbins_discretize"):    FeatureHandler.handle_kbins_discretize,
    ("feature", "hash_encode"):         FeatureHandler.handle_hash_encode,
    ("feature", "ordinal_encode"):      FeatureHandler.handle_ordinal_encode,
    ("feature", "label_binarize"):      FeatureHandler.handle_label_binarize,
    ("feature", "exponential_transform"):FeatureHandler.handle_exponential_transform,
    ("feature", "sin_cos_hour"):        FeatureHandler.handle_sin_cos_hour,
    ("feature", "is_weekend"):          FeatureHandler.handle_is_weekend,
    ("feature", "is_holiday"):          FeatureHandler.handle_is_holiday,
    ("feature", "time_since"):          FeatureHandler.handle_time_since,
    ("feature", "distance_from_mean"):  FeatureHandler.handle_distance_from_mean,
    ("feature", "clip_features"):       FeatureHandler.handle_clip_features,
    ("feature", "auto_feature_select"): FeatureHandler.handle_auto_feature_select,
    ("feature", "feature_cross"):       FeatureHandler.handle_feature_cross,
    ("feature", "rolling_stats_features"):FeatureHandler.handle_rolling_stats_features,
    ("feature", "ewm_features"):        FeatureHandler.handle_ewm_features,
    ("feature", "target_binary_encode"):FeatureHandler.handle_target_binary_encode,
    ("feature", "zscore_features"):     FeatureHandler.handle_zscore_features,
    ("feature", "boxcox_transform"):    FeatureHandler.handle_boxcox_transform,
    ("feature", "yeo_johnson_transform"):FeatureHandler.handle_yeo_johnson_transform,
    ("feature", "winsorize"):           FeatureHandler.handle_winsorize,
    # NLP / Text preprocessing
    ("nlp", "text_clean"):           NlpHandler.handle_text_clean,
    ("nlp", "remove_stopwords"):     NlpHandler.handle_remove_stopwords,
    ("nlp", "tokenize"):             NlpHandler.handle_tokenize,
    ("nlp", "tfidf"):                NlpHandler.handle_tfidf,
    ("nlp", "bow"):                  NlpHandler.handle_bow,
    ("nlp", "ngrams"):               NlpHandler.handle_ngrams,
    ("nlp", "regex_extract"):        NlpHandler.handle_regex_extract,
    ("nlp", "sentiment_score"):      NlpHandler.handle_sentiment_score,
    ("nlp", "word_frequency"):       NlpHandler.handle_word_frequency,
    ("nlp", "text_similarity"):      NlpHandler.handle_text_similarity,
    ("nlp", "vocab_stats"):          NlpHandler.handle_vocab_stats,
    ("nlp", "text_normalize"):       NlpHandler.handle_text_normalize,
    ("nlp", "language_detect"):      NlpHandler.handle_language_detect,
    ("nlp", "hash_vectorize"):       NlpHandler.handle_hash_vectorize,
    ("nlp", "text_encode"):          NlpHandler.handle_text_encode,
    ("nlp", "keyword_extract"):      NlpHandler.handle_keyword_extract,
    ("nlp", "char_features"):        NlpHandler.handle_char_features,
    ("nlp", "sentence_features"):    NlpHandler.handle_sentence_features,
    ("nlp", "readability_score"):    NlpHandler.handle_readability_score,
    ("nlp", "text_dedup"):           NlpHandler.handle_text_dedup,
    ("nlp", "emoji_features"):       NlpHandler.handle_emoji_features,
    ("nlp", "text_mask_pii"):        NlpHandler.handle_text_mask_pii,
    ("nlp", "text_augment"):         NlpHandler.handle_text_augment,
    ("nlp", "collocations"):         NlpHandler.handle_collocations,
    ("nlp", "word_cloud"):           NlpHandler.handle_word_cloud,
    ("nlp", "text_filter"):          NlpHandler.handle_text_filter,
    ("nlp", "class_balance_text"):   NlpHandler.handle_class_balance_text,
    ("nlp", "text_chunk"):           NlpHandler.handle_text_chunk,
    ("nlp", "spelling_features"):    NlpHandler.handle_spelling_features,
    ("nlp", "text_concat"):          NlpHandler.handle_text_concat,
    ("nlp", "text_replace"):         NlpHandler.handle_text_replace,
    ("nlp", "text_split_sentences"): NlpHandler.handle_text_split_sentences,
    ("nlp", "text_oversample"):      NlpHandler.handle_text_oversample,
    ("nlp", "doc_term_matrix"):      NlpHandler.handle_doc_term_matrix,
    ("nlp", "text_window"):          NlpHandler.handle_text_window,
    ("nlp", "text_label_rules"):     NlpHandler.handle_text_label_rules,
    ("nlp", "word_overlap"):         NlpHandler.handle_word_overlap,
    ("nlp", "text_truncate_pad"):    NlpHandler.handle_text_truncate_pad,
    ("nlp", "text_length_dist"):     NlpHandler.handle_text_length_dist,
    ("nlp", "text_unique_words"):    NlpHandler.handle_text_unique_words,
    ("nlp", "text_dedup_exact"):     NlpHandler.handle_text_dedup_exact,
    ("nlp", "text_to_paragraphs"):   NlpHandler.handle_text_to_paragraphs,
    ("nlp", "text_count_pattern"):   NlpHandler.handle_text_count_pattern,
    ("nlp", "text_summary_report"):  NlpHandler.handle_text_summary_report,
    ("nlp", "text_stratified_sample"): NlpHandler.handle_text_stratified_sample,
    ("nlp", "text_ngram_frequency"):   NlpHandler.handle_text_ngram_frequency,
    ("nlp", "text_extract_numbers"):   NlpHandler.handle_text_extract_numbers,
    ("nlp", "text_remove_rare"):       NlpHandler.handle_text_remove_rare,
    ("nlp", "text_pos_patterns"):      NlpHandler.handle_text_pos_patterns,
    ("nlp", "text_diversity_index"):   NlpHandler.handle_text_diversity_index,
    # Analysis (smart, high-level)
    ("analysis", "compare_extremes"):     AnalysisHandler.handle_compare_extremes,
    ("analysis", "deep_profile"):         AnalysisHandler.handle_deep_profile,
    ("analysis", "group_insights"):       AnalysisHandler.handle_group_insights,
    ("analysis", "anomaly_detect"):       AnalysisHandler.handle_anomaly_detect,
    ("analysis", "data_quality"):         AnalysisHandler.handle_data_quality,
    ("analysis", "correlation_insights"): AnalysisHandler.handle_correlation_insights,
    ("analysis", "compare_columns"):      AnalysisHandler.handle_compare_columns,
    ("analysis", "trend_detect"):         AnalysisHandler.handle_trend_detect,
    ("analysis", "segment_analysis"):     AnalysisHandler.handle_segment_analysis,
    ("analysis", "auto_eda"):             AnalysisHandler.handle_auto_eda,
    ("analysis", "cluster_kmeans"):       AnalysisHandler.handle_cluster_kmeans,
    ("analysis", "pca_2d"):               AnalysisHandler.handle_pca_2d,
    ("analysis", "outlier_isolation_forest"): AnalysisHandler.handle_outlier_isolation_forest,
    ("analysis", "feature_selection_auto"): AnalysisHandler.handle_feature_selection_auto,
    ("analysis", "distribution_analysis"): AnalysisHandler.handle_distribution_analysis,
    ("analysis", "missing_value_analysis"): AnalysisHandler.handle_missing_value_analysis,
    ("analysis", "categorical_analysis"): AnalysisHandler.handle_categorical_analysis,
    ("analysis", "numeric_summary"):      AnalysisHandler.handle_numeric_summary,
    ("analysis", "hypothesis_test"):      AnalysisHandler.handle_hypothesis_test,
    ("analysis", "regression_quick"):     AnalysisHandler.handle_regression_quick,
    ("analysis", "top_n_analysis"):       AnalysisHandler.handle_top_n_analysis,
    ("analysis", "bottom_n_analysis"):    AnalysisHandler.handle_bottom_n_analysis,
    ("analysis", "percentile_analysis"):  AnalysisHandler.handle_percentile_analysis,
    ("analysis", "variance_analysis"):    AnalysisHandler.handle_variance_analysis,
    ("analysis", "change_point_detect"):  AnalysisHandler.handle_change_point_detect,
    ("analysis", "target_analysis"):      AnalysisHandler.handle_target_analysis,
    ("analysis", "multicollinearity_check"): AnalysisHandler.handle_multicollinearity_check,
    ("analysis", "ab_test"):              AnalysisHandler.handle_ab_test,
    ("analysis", "pareto_analysis"):      AnalysisHandler.handle_pareto_analysis,
    ("analysis", "data_completeness"):    AnalysisHandler.handle_data_completeness,
    ("analysis", "seasonality_detect"):   AnalysisHandler.handle_seasonality_detect,
    ("analysis", "cluster_profile"):      AnalysisHandler.handle_cluster_profile,
    ("analysis", "feature_interaction"):  AnalysisHandler.handle_feature_interaction,
    ("analysis", "cohort_analysis"):      AnalysisHandler.handle_cohort_analysis,
    ("analysis", "rfm_analysis"):         AnalysisHandler.handle_rfm_analysis,
    ("analysis", "gap_analysis"):         AnalysisHandler.handle_gap_analysis,
    ("analysis", "benchmark_compare"):    AnalysisHandler.handle_benchmark_compare,
    ("analysis", "sensitivity_analysis"): AnalysisHandler.handle_sensitivity_analysis,
    ("analysis", "correlation_network"):  AnalysisHandler.handle_correlation_network,
    ("analysis", "feature_drift"):        AnalysisHandler.handle_feature_drift,
    ("analysis", "sample_bias_check"):    AnalysisHandler.handle_sample_bias_check,
    ("analysis", "effect_size"):          AnalysisHandler.handle_effect_size,
    ("analysis", "bootstrap_ci"):         AnalysisHandler.handle_bootstrap_ci,
    ("analysis", "cross_correlation"):    AnalysisHandler.handle_cross_correlation,
    ("analysis", "survival_curve"):       AnalysisHandler.handle_survival_curve,
    ("analysis", "concentration_analysis"): AnalysisHandler.handle_concentration_analysis,
    ("analysis", "diminishing_returns"):  AnalysisHandler.handle_diminishing_returns,
    ("analysis", "categorical_target_crosstab"): AnalysisHandler.handle_categorical_target_crosstab,
    ("analysis", "prediction_baseline"):  AnalysisHandler.handle_prediction_baseline,
    ("analysis", "data_readiness_score"): AnalysisHandler.handle_data_readiness_score,
}


def get_handler(category: str, sub_intent: str) -> HandlerFunc | None:
    """Look up handler by (category, sub_intent). Returns None if not found."""
    return HANDLER_REGISTRY.get((category, sub_intent))
