"""Handler registry — maps (category, sub_intent) to handler functions."""
from __future__ import annotations

from typing import Callable

import pandas as pd

from api.handlers.base import HandlerResult
from api.handlers import stats, clean, transform, viz, feature, nlp, analysis

HandlerFunc = Callable[[pd.DataFrame, dict], HandlerResult]

HANDLER_REGISTRY: dict[tuple[str, str], HandlerFunc] = {
    # Stats
    ("stats", "describe"):          stats.handle_describe,
    ("stats", "shape"):             stats.handle_shape,
    ("stats", "null_report"):       stats.handle_null_report,
    ("stats", "value_counts"):      stats.handle_value_counts,
    ("stats", "unique_values"):     stats.handle_unique_values,
    ("stats", "dtypes"):            stats.handle_dtypes,
    ("stats", "correlation"):       stats.handle_correlation,
    ("stats", "skewness"):          stats.handle_skewness,
    ("stats", "outlier_report"):    stats.handle_outlier_report,
    ("stats", "duplicate_report"):  stats.handle_duplicate_report,
    ("stats", "cross_tab"):         stats.handle_cross_tab,
    ("stats", "percentile"):        stats.handle_percentile,
    ("stats", "normality_test"):    stats.handle_normality_test,
    ("stats", "class_balance"):     stats.handle_class_balance,
    ("stats", "top_correlations"):  stats.handle_top_correlations,
    ("stats", "kurtosis"):          stats.handle_kurtosis,
    ("stats", "zero_report"):       stats.handle_zero_report,
    ("stats", "cardinality_report"):stats.handle_cardinality_report,
    ("stats", "mode_report"):       stats.handle_mode_report,
    ("stats", "variance_report"):   stats.handle_variance_report,
    ("stats", "range_report"):      stats.handle_range_report,
    ("stats", "iqr_report"):        stats.handle_iqr_report,
    ("stats", "z_score_report"):    stats.handle_z_score_report,
    ("stats", "chi2_test"):         stats.handle_chi2_test,
    ("stats", "t_test"):            stats.handle_t_test,
    ("stats", "anova_test"):        stats.handle_anova_test,
    ("stats", "mann_whitney"):      stats.handle_mann_whitney,
    ("stats", "ks_test"):           stats.handle_ks_test,
    ("stats", "frequency_table"):   stats.handle_frequency_table,
    ("stats", "coefficient_variation"): stats.handle_coefficient_variation,
    ("stats", "correlation_rank"):  stats.handle_correlation_rank,
    ("stats", "entropy_report"):    stats.handle_entropy_report,
    ("stats", "gini_report"):       stats.handle_gini_report,
    ("stats", "missing_pattern"):   stats.handle_missing_pattern,
    ("stats", "quantile_detail"):   stats.handle_quantile_detail,
    ("stats", "group_stats"):       stats.handle_group_stats,
    ("stats", "column_compare"):    stats.handle_column_compare,
    ("stats", "mutual_info_report"):stats.handle_mutual_info_report,
    ("stats", "summary_extended"):  stats.handle_summary_extended,
    ("stats", "ratio_report"):      stats.handle_ratio_report,
    ("stats", "distribution_fit"):  stats.handle_distribution_fit,
    ("stats", "stability_report"):  stats.handle_stability_report,
    ("stats", "pairwise_stats"):    stats.handle_pairwise_stats,
    ("stats", "time_stats"):        stats.handle_time_stats,
    ("stats", "top_bottom_values"): stats.handle_top_bottom_values,
    ("stats", "memory_report"):     stats.handle_memory_report,
    ("stats", "cluster_tendency"):  stats.handle_cluster_tendency,
    ("stats", "sparsity_report"):   stats.handle_sparsity_report,
    ("stats", "data_sample"):       stats.handle_data_sample,
    ("stats", "normality_comprehensive"): stats.handle_normality_comprehensive,

    # Clean
    ("clean", "drop_nulls"):        clean.handle_drop_nulls,
    ("clean", "fill_nulls"):        clean.handle_fill_nulls,
    ("clean", "remove_duplicates"): clean.handle_remove_duplicates,
    ("clean", "fix_dtypes"):        clean.handle_fix_dtypes,
    ("clean", "rename_column"):     clean.handle_rename_column,
    ("clean", "drop_column"):       clean.handle_drop_column,
    ("clean", "strip_whitespace"):    clean.handle_strip_whitespace,
    ("clean", "replace_values"):     clean.handle_replace_values,
    ("clean", "lowercase_columns"):  clean.handle_lowercase_columns,
    ("clean", "drop_constant"):      clean.handle_drop_constant,
    ("clean", "clip_outliers"):       clean.handle_clip_outliers,
    ("clean", "change_dtype"):       clean.handle_change_dtype,
    ("clean", "fill_interpolate"):   clean.handle_fill_interpolate,
    ("clean", "remove_outliers"):    clean.handle_remove_outliers,
    ("clean", "lowercase_values"):   clean.handle_lowercase_values,
    ("clean", "map_values"):         clean.handle_map_values,
    ("clean", "reset_index"):        clean.handle_reset_index,
    ("clean", "fill_with_value"):    clean.handle_fill_with_value,
    ("clean", "deduplicate_by"):     clean.handle_deduplicate_by,
    ("clean", "drop_id_columns"):    clean.handle_drop_id_columns,
    ("clean", "fix_numeric_strings"):   clean.handle_fix_numeric_strings,
    ("clean", "clean_column_names"):    clean.handle_clean_column_names,
    ("clean", "remove_empty_rows"):     clean.handle_remove_empty_rows,
    ("clean", "fill_mode"):             clean.handle_fill_mode,
    ("clean", "fill_forward_backward"): clean.handle_fill_forward_backward,
    ("clean", "fix_boolean"):           clean.handle_fix_boolean,
    ("clean", "fix_encoding"):          clean.handle_fix_encoding,
    ("clean", "remove_html_tags"):      clean.handle_remove_html_tags,
    ("clean", "clean_currency"):        clean.handle_clean_currency,
    ("clean", "standardize_dates"):     clean.handle_standardize_dates,
    ("clean", "remove_non_ascii"):      clean.handle_remove_non_ascii,
    ("clean", "remove_special_chars"):  clean.handle_remove_special_chars,
    ("clean", "normalize_text_case"):   clean.handle_normalize_text_case,
    ("clean", "cap_outliers_percentile"): clean.handle_cap_outliers_percentile,
    ("clean", "fill_median_by_group"):  clean.handle_fill_median_by_group,
    ("clean", "remove_zero_rows"):      clean.handle_remove_zero_rows,
    ("clean", "remove_negative"):       clean.handle_remove_negative,
    ("clean", "standardize_categories"): clean.handle_standardize_categories,
    ("clean", "remove_high_null_cols"): clean.handle_remove_high_null_cols,
    ("clean", "clean_phone_numbers"):   clean.handle_clean_phone_numbers,
    ("clean", "split_name"):            clean.handle_split_name,
    ("clean", "fix_whitespace_names"):  clean.handle_fix_whitespace_names,
    ("clean", "remove_urls"):           clean.handle_remove_urls,
    ("clean", "remove_emails"):         clean.handle_remove_emails,
    ("clean", "fix_mixed_types"):       clean.handle_fix_mixed_types,
    ("clean", "fill_with_distribution"): clean.handle_fill_with_distribution,
    ("clean", "remove_rare_categories"): clean.handle_remove_rare_categories,
    ("clean", "dedup_keep_latest"):     clean.handle_dedup_keep_latest,
    ("clean", "fix_date_outliers"):     clean.handle_fix_date_outliers,
    ("clean", "clean_text_whitespace"): clean.handle_clean_text_whitespace,

    # Transform
    ("transform", "filter"):         transform.handle_filter,
    ("transform", "assign_value"):   transform.handle_assign_value,
    ("transform", "sort"):           transform.handle_sort,
    ("transform", "groupby_agg"):    transform.handle_groupby_agg,
    ("transform", "add_column"):     transform.handle_add_column,
    ("transform", "encode_label"):   transform.handle_encode_label,
    ("transform", "encode_onehot"):  transform.handle_encode_onehot,
    ("transform", "scale_minmax"):   transform.handle_scale_minmax,
    ("transform", "scale_standard"): transform.handle_scale_standard,
    ("transform", "bin_column"):     transform.handle_bin_column,
    ("transform", "inject_null"):    transform.handle_inject_null,
    ("transform", "sample_rows"):    transform.handle_sample_rows,
    ("transform", "head"):             transform.handle_head,
    ("transform", "tail"):             transform.handle_tail,
    ("transform", "pivot"):            transform.handle_pivot,
    ("transform", "melt"):             transform.handle_melt,
    ("transform", "scale_robust"):     transform.handle_scale_robust,
    ("transform", "nlargest"):         transform.handle_nlargest,
    ("transform", "nsmallest"):        transform.handle_nsmallest,
    ("transform", "rank"):             transform.handle_rank,
    ("transform", "cumulative"):       transform.handle_cumulative,
    ("transform", "rolling"):          transform.handle_rolling,
    ("transform", "round_values"):     transform.handle_round_values,
    ("transform", "split_column"):     transform.handle_split_column,
    ("transform", "concat_columns"):   transform.handle_concat_columns,
    ("transform", "qcut"):             transform.handle_qcut,
    ("transform", "merge"):            transform.handle_merge,
    ("transform", "transpose"):        transform.handle_transpose,
    ("transform", "drop_rows"):        transform.handle_drop_rows,
    ("transform", "shuffle"):          transform.handle_shuffle,
    ("transform", "train_test_split"): transform.handle_train_test_split,
    ("transform", "clip"):             transform.handle_clip,
    ("transform", "where"):            transform.handle_where,
    ("transform", "explode"):          transform.handle_explode,
    ("transform", "encode_binary"):    transform.handle_encode_binary,
    ("transform", "pct_change"):       transform.handle_pct_change,
    ("transform", "normalize_pct"):    transform.handle_normalize_pct,
    ("transform", "apply_expr"):       transform.handle_apply_expr,
    ("transform", "flatten_columns"):  transform.handle_flatten_columns,
    ("transform", "resample"):         transform.handle_resample,
    ("transform", "cross_join"):       transform.handle_cross_join,
    ("transform", "encode_ordinal"):   transform.handle_encode_ordinal,
    ("transform", "shift_column"):     transform.handle_shift_column,
    ("transform", "winsorize"):        transform.handle_winsorize,
    ("transform", "stack_columns"):    transform.handle_stack_columns,
    ("transform", "unstack_column"):   transform.handle_unstack_column,
    ("transform", "reorder_columns"):  transform.handle_reorder_columns,
    ("transform", "duplicate_column"): transform.handle_duplicate_column,
    ("transform", "fill_forward"):     transform.handle_fill_forward,
    ("transform", "interpolate_values"): transform.handle_interpolate_values,

    # Viz
    ("viz", "bar_chart"):          viz.handle_bar_chart,
    ("viz", "histogram"):          viz.handle_histogram,
    ("viz", "scatter"):            viz.handle_scatter,
    ("viz", "line_chart"):         viz.handle_line_chart,
    ("viz", "box_plot"):           viz.handle_box_plot,
    ("viz", "violin_plot"):        viz.handle_violin_plot,
    ("viz", "heatmap"):            viz.handle_heatmap,
    ("viz", "pie_chart"):          viz.handle_pie_chart,
    ("viz", "pairplot"):           viz.handle_pairplot,
    ("viz", "missing_heatmap"):    viz.handle_missing_heatmap,
    ("viz", "count_plot"):         viz.handle_count_plot,
    ("viz", "time_series"):        viz.handle_time_series,
    ("viz", "bubble_chart"):       viz.handle_bubble_chart,
    ("viz", "treemap"):            viz.handle_treemap,
    ("viz", "sunburst"):           viz.handle_sunburst,
    ("viz", "parallel_coords"):    viz.handle_parallel_coords,
    ("viz", "distribution"):       viz.handle_distribution,
    ("viz", "stacked_bar"):        viz.handle_stacked_bar,
    ("viz", "area_chart"):         viz.handle_area_chart,
    ("viz", "qq_plot"):            viz.handle_qq_plot,
    ("viz", "density_plot"):       viz.handle_density_plot,
    ("viz", "strip_plot"):         viz.handle_strip_plot,
    ("viz", "donut_chart"):        viz.handle_donut_chart,
    ("viz", "grouped_bar"):        viz.handle_grouped_bar,
    ("viz", "percent_bar"):        viz.handle_percent_bar,
    ("viz", "pareto_chart"):       viz.handle_pareto_chart,
    ("viz", "waterfall_chart"):    viz.handle_waterfall_chart,
    ("viz", "funnel_chart"):       viz.handle_funnel_chart,
    ("viz", "radar_chart"):        viz.handle_radar_chart,
    ("viz", "lollipop_chart"):     viz.handle_lollipop_chart,
    ("viz", "dual_axis"):          viz.handle_dual_axis,
    ("viz", "histogram_2d"):       viz.handle_histogram_2d,
    ("viz", "ecdf_plot"):          viz.handle_ecdf_plot,
    ("viz", "step_chart"):         viz.handle_step_chart,
    ("viz", "error_bar_chart"):    viz.handle_error_bar_chart,
    ("viz", "ridgeline"):          viz.handle_ridgeline,
    ("viz", "dot_plot"):           viz.handle_dot_plot,
    ("viz", "polar_chart"):        viz.handle_polar_chart,
    ("viz", "sankey_chart"):       viz.handle_sankey_chart,
    ("viz", "candlestick"):        viz.handle_candlestick,
    ("viz", "contour_plot"):       viz.handle_contour_plot,
    ("viz", "cumulative_line"):    viz.handle_cumulative_line,
    ("viz", "null_bar"):           viz.handle_null_bar,
    ("viz", "top_n_bar"):          viz.handle_top_n_bar,
    ("viz", "correlation_scatter"): viz.handle_correlation_scatter,
    ("viz", "range_plot"):         viz.handle_range_plot,
    ("viz", "swarm_plot"):         viz.handle_swarm_plot,
    ("viz", "comparison_bar"):     viz.handle_comparison_bar,
    ("viz", "marimekko"):          viz.handle_marimekko,
    ("viz", "gauge_chart"):        viz.handle_gauge_chart,

    # Feature
    ("feature", "feature_importance"):  feature.handle_feature_importance,
    ("feature", "pca"):                 feature.handle_pca,
    ("feature", "correlation_filter"):  feature.handle_correlation_filter,
    ("feature", "log_transform"):       feature.handle_log_transform,
    ("feature", "variance_filter"):     feature.handle_variance_filter,
    ("feature", "polynomial_features"): feature.handle_polynomial_features,
    ("feature", "datetime_features"):   feature.handle_datetime_features,
    ("feature", "target_encode"):       feature.handle_target_encode,
    ("feature", "select_k_best"):       feature.handle_select_k_best,
    ("feature", "power_transform"):     feature.handle_power_transform,
    ("feature", "ratio_features"):      feature.handle_ratio_features,
    ("feature", "frequency_encode"):    feature.handle_frequency_encode,
    ("feature", "cyclical_encode"):     feature.handle_cyclical_encode,
    ("feature", "sqrt_transform"):      feature.handle_sqrt_transform,
    ("feature", "mutual_info"):         feature.handle_mutual_info,
    ("feature", "lag_features"):        feature.handle_lag_features,
    ("feature", "text_features"):       feature.handle_text_features,
    ("feature", "quantile_transform"):  feature.handle_quantile_transform,
    ("feature", "diff_features"):       feature.handle_diff_features,
    ("feature", "aggregation_features"):feature.handle_aggregation_features,
    ("feature", "log1p_transform"):     feature.handle_log1p_transform,
    ("feature", "interaction_features"):feature.handle_interaction_features,
    ("feature", "bin_numeric"):         feature.handle_bin_numeric,
    ("feature", "abs_transform"):       feature.handle_abs_transform,
    ("feature", "reciprocal_transform"):feature.handle_reciprocal_transform,
    ("feature", "count_encode"):        feature.handle_count_encode,
    ("feature", "rare_category_encode"):feature.handle_rare_category_encode,
    ("feature", "is_null_features"):    feature.handle_is_null_features,
    ("feature", "is_zero_features"):    feature.handle_is_zero_features,
    ("feature", "rank_transform"):      feature.handle_rank_transform,
    ("feature", "kbins_discretize"):    feature.handle_kbins_discretize,
    ("feature", "hash_encode"):         feature.handle_hash_encode,
    ("feature", "ordinal_encode"):      feature.handle_ordinal_encode,
    ("feature", "label_binarize"):      feature.handle_label_binarize,
    ("feature", "exponential_transform"):feature.handle_exponential_transform,
    ("feature", "sin_cos_hour"):        feature.handle_sin_cos_hour,
    ("feature", "is_weekend"):          feature.handle_is_weekend,
    ("feature", "is_holiday"):          feature.handle_is_holiday,
    ("feature", "time_since"):          feature.handle_time_since,
    ("feature", "distance_from_mean"):  feature.handle_distance_from_mean,
    ("feature", "clip_features"):       feature.handle_clip_features,
    ("feature", "auto_feature_select"): feature.handle_auto_feature_select,
    ("feature", "feature_cross"):       feature.handle_feature_cross,
    ("feature", "rolling_stats_features"):feature.handle_rolling_stats_features,
    ("feature", "ewm_features"):        feature.handle_ewm_features,
    ("feature", "target_binary_encode"):feature.handle_target_binary_encode,
    ("feature", "zscore_features"):     feature.handle_zscore_features,
    ("feature", "boxcox_transform"):    feature.handle_boxcox_transform,
    ("feature", "yeo_johnson_transform"):feature.handle_yeo_johnson_transform,
    ("feature", "winsorize"):           feature.handle_winsorize,

    # NLP / Text preprocessing
    ("nlp", "text_clean"):           nlp.handle_text_clean,
    ("nlp", "remove_stopwords"):     nlp.handle_remove_stopwords,
    ("nlp", "tokenize"):             nlp.handle_tokenize,
    ("nlp", "tfidf"):                nlp.handle_tfidf,
    ("nlp", "bow"):                  nlp.handle_bow,
    ("nlp", "ngrams"):               nlp.handle_ngrams,
    ("nlp", "regex_extract"):        nlp.handle_regex_extract,
    ("nlp", "sentiment_score"):      nlp.handle_sentiment_score,
    ("nlp", "word_frequency"):       nlp.handle_word_frequency,
    ("nlp", "text_similarity"):      nlp.handle_text_similarity,
    ("nlp", "vocab_stats"):          nlp.handle_vocab_stats,
    ("nlp", "text_normalize"):       nlp.handle_text_normalize,
    ("nlp", "language_detect"):      nlp.handle_language_detect,
    ("nlp", "hash_vectorize"):       nlp.handle_hash_vectorize,
    ("nlp", "text_encode"):          nlp.handle_text_encode,
    ("nlp", "keyword_extract"):      nlp.handle_keyword_extract,
    ("nlp", "char_features"):        nlp.handle_char_features,
    ("nlp", "sentence_features"):    nlp.handle_sentence_features,
    ("nlp", "readability_score"):    nlp.handle_readability_score,
    ("nlp", "text_dedup"):           nlp.handle_text_dedup,
    ("nlp", "emoji_features"):       nlp.handle_emoji_features,
    ("nlp", "text_mask_pii"):        nlp.handle_text_mask_pii,
    ("nlp", "text_augment"):         nlp.handle_text_augment,
    ("nlp", "collocations"):         nlp.handle_collocations,
    ("nlp", "word_cloud"):           nlp.handle_word_cloud,
    ("nlp", "text_filter"):          nlp.handle_text_filter,
    ("nlp", "class_balance_text"):   nlp.handle_class_balance_text,
    ("nlp", "text_chunk"):           nlp.handle_text_chunk,
    ("nlp", "spelling_features"):    nlp.handle_spelling_features,
    ("nlp", "text_concat"):          nlp.handle_text_concat,
    ("nlp", "text_replace"):         nlp.handle_text_replace,
    ("nlp", "text_split_sentences"): nlp.handle_text_split_sentences,
    ("nlp", "text_oversample"):      nlp.handle_text_oversample,
    ("nlp", "doc_term_matrix"):      nlp.handle_doc_term_matrix,
    ("nlp", "text_window"):          nlp.handle_text_window,
    ("nlp", "text_label_rules"):     nlp.handle_text_label_rules,
    ("nlp", "word_overlap"):         nlp.handle_word_overlap,
    ("nlp", "text_truncate_pad"):    nlp.handle_text_truncate_pad,
    ("nlp", "text_length_dist"):     nlp.handle_text_length_dist,
    ("nlp", "text_unique_words"):    nlp.handle_text_unique_words,
    ("nlp", "text_dedup_exact"):     nlp.handle_text_dedup_exact,
    ("nlp", "text_to_paragraphs"):   nlp.handle_text_to_paragraphs,
    ("nlp", "text_count_pattern"):   nlp.handle_text_count_pattern,
    ("nlp", "text_summary_report"):  nlp.handle_text_summary_report,
    ("nlp", "text_stratified_sample"): nlp.handle_text_stratified_sample,
    ("nlp", "text_ngram_frequency"):   nlp.handle_text_ngram_frequency,
    ("nlp", "text_extract_numbers"):   nlp.handle_text_extract_numbers,
    ("nlp", "text_remove_rare"):       nlp.handle_text_remove_rare,
    ("nlp", "text_pos_patterns"):      nlp.handle_text_pos_patterns,
    ("nlp", "text_diversity_index"):   nlp.handle_text_diversity_index,

    # Analysis (smart, high-level)
    ("analysis", "compare_extremes"):     analysis.handle_compare_extremes,
    ("analysis", "deep_profile"):         analysis.handle_deep_profile,
    ("analysis", "group_insights"):       analysis.handle_group_insights,
    ("analysis", "anomaly_detect"):       analysis.handle_anomaly_detect,
    ("analysis", "data_quality"):         analysis.handle_data_quality,
    ("analysis", "correlation_insights"): analysis.handle_correlation_insights,
    ("analysis", "compare_columns"):      analysis.handle_compare_columns,
    ("analysis", "trend_detect"):         analysis.handle_trend_detect,
    ("analysis", "segment_analysis"):     analysis.handle_segment_analysis,
    ("analysis", "auto_eda"):             analysis.handle_auto_eda,
    ("analysis", "cluster_kmeans"):       analysis.handle_cluster_kmeans,
    ("analysis", "pca_2d"):               analysis.handle_pca_2d,
    ("analysis", "outlier_isolation_forest"): analysis.handle_outlier_isolation_forest,
    ("analysis", "feature_selection_auto"): analysis.handle_feature_selection_auto,
    ("analysis", "distribution_analysis"): analysis.handle_distribution_analysis,
    ("analysis", "missing_value_analysis"): analysis.handle_missing_value_analysis,
    ("analysis", "categorical_analysis"): analysis.handle_categorical_analysis,
    ("analysis", "numeric_summary"):      analysis.handle_numeric_summary,
    ("analysis", "hypothesis_test"):      analysis.handle_hypothesis_test,
    ("analysis", "regression_quick"):     analysis.handle_regression_quick,
    ("analysis", "top_n_analysis"):       analysis.handle_top_n_analysis,
    ("analysis", "bottom_n_analysis"):    analysis.handle_bottom_n_analysis,
    ("analysis", "percentile_analysis"):  analysis.handle_percentile_analysis,
    ("analysis", "variance_analysis"):    analysis.handle_variance_analysis,
    ("analysis", "change_point_detect"):  analysis.handle_change_point_detect,
    ("analysis", "target_analysis"):      analysis.handle_target_analysis,
    ("analysis", "multicollinearity_check"): analysis.handle_multicollinearity_check,
    ("analysis", "ab_test"):              analysis.handle_ab_test,
    ("analysis", "pareto_analysis"):      analysis.handle_pareto_analysis,
    ("analysis", "data_completeness"):    analysis.handle_data_completeness,
    ("analysis", "seasonality_detect"):   analysis.handle_seasonality_detect,
    ("analysis", "cluster_profile"):      analysis.handle_cluster_profile,
    ("analysis", "feature_interaction"):  analysis.handle_feature_interaction,
    ("analysis", "cohort_analysis"):      analysis.handle_cohort_analysis,
    ("analysis", "rfm_analysis"):         analysis.handle_rfm_analysis,
    ("analysis", "gap_analysis"):         analysis.handle_gap_analysis,
    ("analysis", "benchmark_compare"):    analysis.handle_benchmark_compare,
    ("analysis", "sensitivity_analysis"): analysis.handle_sensitivity_analysis,
    ("analysis", "correlation_network"):  analysis.handle_correlation_network,
    ("analysis", "feature_drift"):        analysis.handle_feature_drift,
    ("analysis", "sample_bias_check"):    analysis.handle_sample_bias_check,
    ("analysis", "effect_size"):          analysis.handle_effect_size,
    ("analysis", "bootstrap_ci"):         analysis.handle_bootstrap_ci,
    ("analysis", "cross_correlation"):    analysis.handle_cross_correlation,
    ("analysis", "survival_curve"):       analysis.handle_survival_curve,
    ("analysis", "concentration_analysis"): analysis.handle_concentration_analysis,
    ("analysis", "diminishing_returns"):  analysis.handle_diminishing_returns,
    ("analysis", "categorical_target_crosstab"): analysis.handle_categorical_target_crosstab,
    ("analysis", "prediction_baseline"):  analysis.handle_prediction_baseline,
    ("analysis", "data_readiness_score"): analysis.handle_data_readiness_score,
}


def get_handler(category: str, sub_intent: str) -> HandlerFunc | None:
    """Look up handler by (category, sub_intent). Returns None if not found."""
    return HANDLER_REGISTRY.get((category, sub_intent))
